
services:
  # Base de dades MySQL (db)
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: math
    ports:
      - "1000:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./back/math.sql:/docker-entrypoint-initdb.d/dades.sql

  # Adminer: Interfaz para gestionar la base de datos
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"

    # Servicio de Laravel
  laravel:
    build: ./back/laravel
    ports:
      - "8000:8000"
    volumes:
    #Quina carpeta LOCAL s'ha de mapejar / veure DINS del contenidor?
      - ./back/laravel:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    #Quan es crea, es poden executar ordres
    command: bash -c "composer install && php artisan key:generate && php artisan migrate &&php artisan serve --host=0.0.0.0"

    #Servicio de Vue
  vue:
    build:
      context: ./web
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
    depends_on:
      - laravel
    environment:
      VUE_APP_API_URL: http://laravel:8000
    command: bash -c "npm install && npm run dev"